# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Developer_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui       import *
from PyQt5.QtCore      import *
from webbrowser import open_new



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setWindowFlags(Qt.WindowStaysOnTopHint)
        MainWindow.setWindowFlag(Qt.FramelessWindowHint)
        MainWindow.setAttribute(Qt.WA_TranslucentBackground)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        MainWindow.setMaximumSize(QtCore.QSize(800, 500))
        

        MainWindow.setStyleSheet("background-image: url(:/image/IMGE/___IMGE.jpg);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"QPushButton:   #pushButton_4 {\n"
"    background-color: red;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: beige;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QLabel{\n"
"    background: rgba(255, 0, 0, 0);\n"
"}")



        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(765, 3, 31, 31))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {background-color: rgb(12, 255, 207, 0);}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/IMGE/red-x-png-10.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(lambda: MainWindow.close())

        self.pushButton_50 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_50.setGeometry(QtCore.QRect(735, 5, 25, 25))
        self.pushButton_50.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        self.pushButton_50.setFont(QFont('Arial', 25))
        self.pushButton_50.setObjectName("pushButton_50")
        self.pushButton_50.clicked.connect(lambda: MainWindow.showMinimized())
        self.pushButton_50.setText("-")
  


        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(380, 0, 15, 500))
        self.frame.setMinimumSize(QtCore.QSize(15, 500))
        self.frame.setMaximumSize(QtCore.QSize(15, 500))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 240, 800, 15))
        self.frame_2.setMinimumSize(QtCore.QSize(800, 15))
        self.frame_2.setMaximumSize(QtCore.QSize(800, 15))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 151, 131))
        self.label.setStyleSheet("image: url(:/image/IMGE/K.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 180, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 439, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(460, 440, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(460, 180, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(210, 10, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(390, 10, 151, 131))
        self.label_3.setStyleSheet("image: url(:/image/IMGE/A.jpg);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 270, 151, 131))
        self.label_3.setStyleSheet("image: url(:/image/IMGE/Z.jpg);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(390, 270, 151, 131))
        self.label_4.setStyleSheet("image: url(:/image/IMGE/N.jpg);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(583, 10, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(610, 270, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(210, 270, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(400, 180, 41, 41))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background: rgb(255, 255, 255,0);\n"
"    border-image: url(:/image/IMGE/10295013511558096452.svg);\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 5px;\n"
"}\n"
"")
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 440, 41, 41))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background: rgb(255, 255, 255,0);\n"
"    border-image: url(:/image/IMGE/10295013511558096452.svg);\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 5px;\n"
"}\n"
"")
    
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setGeometry(QtCore.QRect(400, 440, 41, 41))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    background: rgb(255, 255, 255,0);\n"
"    border-image: url(:/image/IMGE/10295013511558096452.svg);\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 5px;\n"
"}\n"
"")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(150, 10, 51, 51))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/image/IMGE/—Pngtree—phone icon_4561566.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(533, 10, 51, 51))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/image/IMGE/—Pngtree—phone icon_4561566.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(550, 270, 51, 51))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/image/IMGE/—Pngtree—phone icon_4561566.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(150, 270, 51, 51))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/image/IMGE/—Pngtree—phone icon_4561566.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setGeometry(QtCore.QRect(200, 80, 41, 41))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    border-image: url(:/image/IMGE/fac.svg);\n"
"    border-radius: 20px;\n"
"    background: rgb(255, 255, 255,0);\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 5px;\n"
"}\n"
"")

        self.pushButton_4.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(200, 150, 41, 41))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    background: rgb(255, 255, 255,0);\n"
"    border-image: url(:/image/IMGE/16983312581574338606.svg);\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 3px;\n"
"}\n"
"")

        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(270, 150, 41, 41))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    background: rgb(255, 255, 255,0);\n"
"    \n"
"    border-image: url(:/image/IMGE/9342375421561032683.svg);\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 3px;\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setGeometry(QtCore.QRect(270, 80, 41, 41))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    border-image: url(:/image/IMGE/14329293221556105345.svg);\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 5px;\n"
"}\n"
"")
   
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setGeometry(QtCore.QRect(600, 80, 41, 41))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    border-image: url(:/image/IMGE/fac.svg);\n"
"    border-radius: 20px;\n"
"    background: rgb(255, 255, 255,0);\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 5px;\n"
"}\n"
"")
        
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setGeometry(QtCore.QRect(600, 150, 41, 41))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    background: rgb(255, 255, 255,0);\n"
"    border-image: url(:/image/IMGE/16983312581574338606.svg);\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 3px;\n"
"}\n"
"")

        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setGeometry(QtCore.QRect(670, 80, 41, 41))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"    border-image: url(:/image/IMGE/14329293221556105345.svg);\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 5px;\n"
"}\n"
"")
      
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setGeometry(QtCore.QRect(670, 150, 41, 41))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"    background: rgb(255, 255, 255,0);\n"
"    \n"
"    border-image: url(:/image/IMGE/9342375421561032683.svg);\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 3px;\n"
"}\n"
"")
    
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setGeometry(QtCore.QRect(600, 340, 41, 41))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"    border-image: url(:/image/IMGE/fac.svg);\n"
"    border-radius: 20px;\n"
"    background: rgb(255, 255, 255,0);\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 5px;\n"
"}\n"
"")
    
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_13.setGeometry(QtCore.QRect(600, 410, 41, 41))
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"    background: rgb(255, 255, 255,0);\n"
"    border-image: url(:/image/IMGE/16983312581574338606.svg);\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 3px;\n"
"}\n"
"")
        
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_14.setGeometry(QtCore.QRect(670, 340, 41, 41))
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"    border-image: url(:/image/IMGE/14329293221556105345.svg);\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 5px;\n"
"}\n"
"")
   
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_15.setGeometry(QtCore.QRect(670, 410, 41, 41))
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"    background: rgb(255, 255, 255,0);\n"
"    \n"
"    border-image: url(:/image/IMGE/9342375421561032683.svg);\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 3px;\n"
"}\n"
"")
      
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_16.setGeometry(QtCore.QRect(200, 340, 41, 41))
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"    border-image: url(:/image/IMGE/fac.svg);\n"
"    border-radius: 20px;\n"
"    background: rgb(255, 255, 255,0);\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 5px;\n"
"}\n"
"")
  
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_17.setGeometry(QtCore.QRect(200, 410, 41, 41))
        self.pushButton_17.setStyleSheet("QPushButton{\n"
"    background: rgb(255, 255, 255,0);\n"
"    border-image: url(:/image/IMGE/16983312581574338606.svg);\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 3px;\n"
"}\n"
"")
        self.pushButton_17.setText("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_18.setGeometry(QtCore.QRect(270, 340, 41, 41))
        self.pushButton_18.setStyleSheet("QPushButton{\n"
"    border-image: url(:/image/IMGE/14329293221556105345.svg);\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 5px;\n"
"}\n"
"")
        
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_19.setGeometry(QtCore.QRect(270, 410, 41, 41))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_19.setStyleSheet("QPushButton{\n"
"    background: rgb(255, 255, 255,0);\n"
"    \n"
"    border-image: url(:/image/IMGE/9342375421561032683.svg);\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 3px;\n"
"}\n"
"")
        self.pushButton_19.setText("")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_20.setGeometry(QtCore.QRect(10, 180, 41, 41))
        self.pushButton_20.setStyleSheet("QPushButton{\n"
"    background: rgb(255, 255, 255,0);\n"
"    border-image: url(:/image/IMGE/10295013511558096452.svg);\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 5px;\n"
"}\n"
"")

        self.pushButton_20.setObjectName("pushButton_20")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        Class_Method.Clic(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "karem Badr"))
        self.label_6.setText(_translate("MainWindow", "Azhaar"))
        self.label_7.setText(_translate("MainWindow", "mohamed"))
        self.label_8.setText(_translate("MainWindow", "Ahmed Ali"))
        self.label_9.setText(_translate("MainWindow", "01115756719"))
        self.label_21.setText(_translate("MainWindow", "01006472752"))
        self.label_22.setText(_translate("MainWindow", "01015144746"))
        self.label_23.setText(_translate("MainWindow", "01005723395"))


class Class_Method:

    @classmethod
    def Wpp_open_Whatsapp(cls, number):
        open_new(f"https://web.whatsapp.com/send?phone=++2{number}")

    @classmethod
    def Wpp_open_facebook(cls, urlname):
        open_new(f"https://facebook.com/{urlname}")

    @classmethod
    def Wpp_open_messenger(cls, urlnumber):
        open_new(f"https://web.facebook.com/messages/t/{urlnumber}")

    @classmethod
    def Wpp_open_gmail(cls, namegmail):
        open_new(f'https://mail.google.com/mail/u/0/?fs=1&tf=cm&cc={namegmail}@gmail.com')
        


    @classmethod
    def Clic(cls, self):
        #__________________________________ FACEBOOK ________________________________________#
        self.pushButton_4.clicked.connect(lambda:cls.Wpp_open_facebook('karem.ak.188'))
        self.pushButton_16.clicked.connect(lambda:cls.Wpp_open_facebook('azhaar.mamdouh'))
        self.pushButton_8.clicked.connect(lambda:cls.Wpp_open_facebook('ahmed.alikamel.566'))
        self.pushButton_12.clicked.connect(lambda:cls.Wpp_open_facebook('amr.fahmy.77964'))

        #__________________________________ WHATSAPP _________________________________________#
        self.pushButton_7.clicked.connect(lambda:cls.Wpp_open_Whatsapp('01115756719'))
        self.pushButton_18.clicked.connect(lambda:cls.Wpp_open_Whatsapp('01005723395'))
        self.pushButton_10.clicked.connect(lambda:cls.Wpp_open_Whatsapp('01006472752'))
        self.pushButton_14.clicked.connect(lambda:cls.Wpp_open_Whatsapp('01015144746'))

        #__________________________________ GMAIL _____________________________________________#
        self.pushButton_5.clicked.connect(lambda:cls.Wpp_open_gmail('Karembadr81'))
        self.pushButton_17.clicked.connect(lambda:cls.Wpp_open_gmail('Azhaarmamdouh054'))
        self.pushButton_9.clicked.connect(lambda:cls.Wpp_open_gmail('ahmedalikamel12'))
        self.pushButton_13.clicked.connect(lambda:cls.Wpp_open_gmail('mohamed01015144746'))
        
        #__________________________________ Messenger __________________________________________#
        self.pushButton_6.clicked.connect(lambda:cls.Wpp_open_messenger('100066653460422'))
        self.pushButton_19.clicked.connect(lambda:cls.Wpp_open_messenger('100018034059029'))
        self.pushButton_11.clicked.connect(lambda:cls.Wpp_open_messenger('100016206739355'))
        self.pushButton_15.clicked.connect(lambda:cls.Wpp_open_messenger('100009734889381'))
        
        #______________________________________ Say _____________________________________________#
        self.pushButton_20.clicked.connect(lambda: Class_Method.Speak('Im Kareem and Im a desktop application developer'))
        self.pushButton_2.clicked.connect(lambda: Class_Method.Speak('Im Azhaar and Im a desktop application developer'))
        self.pushButton.clicked.connect(lambda: Class_Method.Speak('Im ahmed and Im a desktop application developer'))
        self.pushButton_3.clicked.connect(lambda: Class_Method.Speak('Im mohamed and Im a desktop application developer'))
    @classmethod
    def Speak(cls, texts):
        from main import Say , Thread
        try:
            t1 = Thread(target=Say,args=(texts, ))
            t1.start()
    
        except:
            None




import Resource_rc
