# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Act.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
SYTLE =  ("QPushButton {\n"
"    \n"
"    \n"
"    background-color: rgb(0, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"    \n"
"    background-color: rgb(0, 196, 255);\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(85, 255, 255);\n"
"    font: bold 18px;\n"
"}")

SYTLE_ =  ("QPushButton {\n"
"    \n"
"    \n"
"    background-color: rgb(0, 255, 255);\n"
"    border-style: outset;\n"
"    border-radius: 7px;\n"
"    border-color: beige;\n"
"    font-size: bold  12px;}\n"
"    padding: 6px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"    \n"
"    background-color: rgb(0, 196, 255);\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(85, 255, 255);\n"

"}")
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 250)
        

        
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/FACEBOOK.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        
        
        MainWindow.setMaximumSize(QtCore.QSize(450, 250))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 451, 251))
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 0, 31, 31))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {background-color: rgb(12, 255, 207, 0);"

"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/IMGE/red-x-png-10.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 100, 241, 41))
        self.lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit.setStyleSheet("QLineEdit{ \n"
"    \n"
"    background-color: rgb(0, 255, 255);\n"
"    border: 3px solid gray;\n"
"    border-radius: 10px;\n"
"    padding: 0 8px;\n"
"    \n"
"    font-size: 16px;}\n"
"  \n"
" QLineEdit:focus { \n"
"    border: 5px solid gray;\n"
"    border-radius: 10px;\n"
"    padding: 0 8px;\n"
"    font-size: 16px;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"       border-color: rgb(85, 255, 255);\n"
"    font: bold 18px;\n"
"}\n"
"")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 170, 181, 41))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet(SYTLE)
                

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(5, 210, 75, 35))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setStyleSheet(SYTLE_)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 25, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(175, 65, 100, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(175, 80, 100, 16))
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 255, 255);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 25, 250, 16))
        self.label_5.setFont(font)
        self.label_5.setFont(QtGui.QFont('Arial', 14))
        self.label_5.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Please Enter Activation Code"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.pushButton_3.setText(_translate("MainWindow", "Developer"))
import Resource_rc
